on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-protos:
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - name: check breaking changes
        uses: bufbuild/buf-breaking-action@v1
